version: '3.6'
services: 
    backend:
        build: ./backend
        ports: 
            - 8080:8080
    frontend:
        build: ./frontend
        ports:
            - 8081:8081
        depends_on: 
            - backend